# declaring variabl at play level
- name: declaring variabl at play level
  hosts: all
  connection: local 
  become: yes
  vars:
   pcs: pendemchandrashekar
  tasks: 
    - name: accessing a variable
      ansible.builtin.debug:
       msg: pcs == {{pcs}}  

# declaring variable in  file
# declaring variable at task level