# declaring variabl at play level
# gitpull ; ansible-playbook -i localhost, vars.yml 
- name: declaring variabl at play level
  hosts: all
  connection: local 
  become: yes
  vars:
   pcs: pendemchandrashekar
  tasks: 
    - name: accessing a variable
      ansible.builtin.debug:
       msg: pcs == {{pcs}}  

# declaring variable in a file
- name: declaring at file level 
  hosts: all 
  connection: local 
  vars_files:
   -vars.yml 
  tasks: 
   - name: declaring a variable in another file
     ansible.builtin.debug:
      msg: pcs == {{pcs}} 

# declaring variable at task level
- name: declaring variable at task level
  hosts: all 
  connection: local 
  tasks: 
   - name: declare and accessing variable
     ansible.builtin.debug:
      msg: pcs == {{pcs}}
     vars: 
      pcs: pendemchandrashekar.online