# declaring variabl at play level
# gitpull ; ansible-playbook -i localhost, vars.yml 
- name: declaring variabl at play level
  hosts: all
  connection: local 
  become: yes
  vars:
   pcs: pendemchandrashekar
  tasks: 
    - name: accessing a variable
      ansible.builtin.debug:
       msg: pcs == {{pcs}}  

# declaring variable in a file
- name: declaring at file level 
  hosts: all 
  connection: local 
  vars_files:
   - vars1.yml 
  tasks: 
   - name: declaring a variable in another file
     ansible.builtin.debug:
      msg: pcs == {{pcs}} 

# declaring variable at task level
- name: declaring variable at task level
  hosts: all 
  connection: local 
  tasks: 
   - name: declare and accessing variable
     ansible.builtin.debug:
      msg: pcs == {{pcs}}
     vars: 
      pcs: pendemchandrashekar.online

# declaring variable at inventory level
- name: declaring variable at inventory level
  hosts: all 
  connection: local 
  tasks: 
   - name: declare and accessing variable
     ansible.builtin.debug:
      msg: pcs == {{pcs}} 
      
# declaring the fact
- name: declaring a fact 
  hosts: all 
  connection: local 
  tasks: 
   - name: accessing fact 
     ansible.builtin.debug: 
      msg: ansible host name == {{ansible_fqdn}}

# run time variable task from output 
- name: output regsiter 
  hosts: all 
  connection: local 
  tasks: 
   - name: run a shell command  
     ansible.builtin.shell: uptime 
     register: out 
   - name: printing the uptime 
     ansible.builtin.debug:
      msg: "{{out.stdout}}"
   - name: setting fact 
     ansible.builtin.set_fact: 
      OUTPUT: "{{out.stdout}}"
      

     