- name: Install the latest version of nginx
  ansible.builtin.yum:
    name: nginx
    state: installed 
  
  
- name: remove directory htttp
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent


