- name: Install the latest version of nginx
  ansible.builtin.yum:
    name: nginx
    state: installed 
  
  
- name: remove directory htttp
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create directory htttp
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name:  download app frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
    dest: /usr/share/nginx/html 
    remote_src: yes

- name: Copy file to nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf 

- name: start nginx service 
  ansible.builtin.service:
   state: restarted 
   name: nginx 
   enabled: yes
