- name: parameters 
  hosts: localhosts 
  connection: local 
  tasks:
    - name: Create or update key/value pair in AWS SSM parameter store
      community.aws.ssm_paramater:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loops:
       - (name: "dev.cart.REDIS_HOST", value: "redis-dev.chandupcs.online")

      