- name: install maven 
  ansible.builtin.yum: 
   name: maven 
   state: installed 

- name: including app pre-req 
  ansible.builtin.include_tasks: "app_prereq.yml"

- name: maven build 
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args: 
   chdir: /app

- name: including systemd task
  ansible.builtin.include_tasks: "systemd.yml"


- name: load schema 
  ansible.builtin.include_tasks: "{{schema_type}}_schema.yml"
  when: schema_load