- name: load mysql schema 
  community.mysql.mysql_db: 
   state: import 
   name: all 
   target: /app/schema/{{component}}.sql 
   login_host: mysql-dev.chandupcs.online 
   login_user: root 
   login_password: "{{root_mysql_password}}"