- name: setup nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed 

- name: including app pre-req
  ansible.builtin.include_tasks: "app_prereq.yml"
  


- name:  download app {{component}} content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip 
    dest: /app
    remote_src: yes 

- name: install nodejs dependices 
  community.general.npm:
   path: /app
   state: latest


- name: including systemd task
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema 
  ansible.builtin.include_tasks: "{{schema_type}}_schema.yml"
  when: schema_load