- name: copy the systemd.service file
  ansible.builtin.template: 
   src: "{{component}}.service"
   dest: /etc/systemd/system/{{component}}.service 

- name: start {{component}} service 
  ansible.builtin.service: 
   name: "{{component}}"
   daemon_reload: yes
   enabled: yes 
   state: restarted 